ARG D_VERSION
FROM docker.elastic.co/beats/filebeat:${D_VERSION}

# USER root

# ADD ./config/filebeat.yml /usr/share/filebeat/filebeat.yml
# RUN chown root /usr/share/filebeat/filebeat.yml
# RUN chmod go-w /usr/share/filebeat/filebeat.yml

 