ARG D_VERSION
FROM docker.elastic.co/kibana/kibana:${D_VERSION}

# USER root

# ADD ./config/kibana.yml /usr/share/kibana/config/kibana.yml

# RUN chown kibana /usr/share/kibana/config/kibana.yml
# RUN chmod go-w /usr/share/kibana/config/kibana.yml

# USER kibana