filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains.docker.container.name: "db"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"

logging.metrics.enabled: false
processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
